### PR TITLE
Make oxauth container wait for consul to become ready

### PR DESCRIPTION
**Pull request by skybert**
- command that can be called from docker-compose.yml making the oxauth
  container hold its horses until the consul container has been properly
  populated (by the config-init container).

- Docker does not have a builtin way of making containers wait for
  others to be "ready", see
  https://docs.docker.com/compose/startup-order/, hence this command.

### CODE REVIEW

**Comment by iromli** [comment]
@skybert can you update this PR?

**Comment by skybert** [comment]
@iromli I'll follow up on this on Monday.

**Comment by skybert** [comment]
@iromli, the PR has been updated.

**Comment by iromli** [comment]
Merged ... thanks @skybert

**Pull request merged**
